- hosts: monitor
  become: yes
  tasks:
    - name: create dir
      file: path=/opt/monitor/prometheus state=directory recurse=yes
    - name: copy prometheus config
      copy:
        src: ../../monitoring/prometheus/prometheus.yml
        dest: /opt/monitor/prometheus/prometheus.yml
    - name: run node_exporter
      docker_container:
        name: node_exporter
        image: prom/node-exporter
        state: started
        restart_policy: unless-stopped
        published_ports:
          - "9100:9100"
    - name: run prometheus
      docker_container:
        name: prometheus
        image: prom/prometheus
        state: started
        restart_policy: unless-stopped
        published_ports:
          - "9090:9090"
        volumes:
          - /opt/monitor/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    - name: run grafana
      docker_container:
        name: grafana
        image: grafana/grafana
        state: started
        restart_policy: unless-stopped
        published_ports:
          - "3000:3000"
        env:
          - GF_SECURITY_ADMIN_PASSWORD=admin
