pipeline {
    agent any
    environment {
        AWS_REGION = 'ap-south-1'
        ECR_REPO = '611410719112.dkr.ecr.ap-south-1.amazonaws.com/spacex-app'
        IMAGE_TAG = "${env.BUILD_NUMBER}"
    }
    stages {
        stage('Checkout') {
            steps { 
                checkout scm 
            }
        }
        stage('Build') {
            steps {
                dir('app') {
                    sh 'docker build -t spacex-app:${IMAGE_TAG} .'
                }
            }
        }
        stage('Test') {
            steps {
                echo "Run tests here (optional)"
            }
        }
        stage('Push to ECR') {
            steps {
                withCredentials([[
                    $class: 'AmazonWebServicesCredentialsBinding',
                    credentialsId: 'aws-creds'
                ]]) {
                    sh '''
                        aws ecr get-login-password --region ${AWS_REGION} | docker login --username AWS --password-stdin ${ECR_REPO%/*}
                        docker tag spacex-app:${IMAGE_TAG} ${ECR_REPO}:${IMAGE_TAG}
                        docker push ${ECR_REPO}:${IMAGE_TAG}
                    '''
                }
            }
        }
        stage('Trigger Deploy') {
            steps {
                sshagent(['ssh-jenkins-app']) {
                    sh """
                        ssh -o StrictHostKeyChecking=no ubuntu@13.235.245.251 \\
                        'docker pull ${ECR_REPO}:${IMAGE_TAG} && \\
                         docker stop spacex || true && \\
                         docker rm spacex || true && \\
                         docker run -d --name spacex -p 5000:5000 ${ECR_REPO}:${IMAGE_TAG}'
                    """
                }
            }
        }
    }
}
